#!/usr/bin/env sh

# Gradle start-up script generated by ChatGPT

APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${0%/*}" && pwd)

DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
GRADLE_WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
if [ ! -f "$GRADLE_WRAPPER_JAR" ]; then
  echo "Missing gradle-wrapper.jar. Please run 'gradle wrapper' on a machine with Gradle installed." >&2
  exit 1
fi

CLASSPATH=$GRADLE_WRAPPER_JAR

java $DEFAULT_JVM_OPTS -classpath $CLASSPATH org.gradle.wrapper.GradleWrapperMain "$@"
